name: Check Namespaces

on: [ push, pull_request ]

jobs:
  composer-psr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/action/setup
        with:
          php-version: 8.4

      - name: Install Composer Dependencies
        run: composer install -q --no-interaction --no-progress --prefer-dist

      - name: Check PSR-4 Mapping
        run: composer dump-autoload --dev --optimize --strict-psr
