name: Validate composer.json

on: [ push, pull_request ]

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/action/setup
        with:
          php-version: 8.4

      - name: Validate composer.json
        run: composer validate --strict
