name: Deploy

on:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ main ]

jobs:
  build:
    name: Deploy
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Make Forge Build Request
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.FORGE_BUILD_URL }})
          if [ $response -eq 200 ]; then
            echo "Successfully sent build request to Forge"
          else
            echo "Forge build request failed with status code: $response"
            exit 1
          fi
