name: EditorConfig

on: [ push, pull_request ]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check EditorConfig Configuration
        run: test -f .editorconfig

      - name: Check Adherence to EditorConfig
        uses: greut/eclint-action@v0
