name: Pint

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

jobs:
  pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/action/setup
        with:
          php-version: 8.4

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style: automatic fixes"
          commit_user_name: Refringe
          commit_user_email: me@refringe.com
          commit_author: Refringe <me@refringe.com>
