name: Rector

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

jobs:
  rector:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/action/setup
        with:
          php-version: 8.4

      - name: Install Composer Dependencies
        run: composer install -q --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Rector Cache
        uses: actions/cache@v4
        with:
          path: .rector/cache
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: mkdir -p .rector/cache

      - name: Execute Rector Analysis
        run: php vendor/bin/rector process --config=rector.php

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "refactor: automatic fixes"
          commit_user_name: Refringe
          commit_user_email: me@refringe.com
          commit_author: Refringe <me@refringe.com>
