name: Security

on: [ push, pull_request ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v5
