name: Typos

on: [ push, pull_request ]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Search For Misspellings
        uses: crate-ci/typos@v1
        with:
          config: ./typos.toml
